// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hgwxxmfvqsxcuydhhjra.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnd3h4bWZ2cXN4Y3V5ZGhoanJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1Mzk3NzksImV4cCI6MjA0OTExNTc3OX0.T2j_n8_UI-caj5a7QGWJzh68bcqnZFB07EN4U8Lq8J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);